### ISSUE TITLE
Milestone 1 To do list

### ISSUE THREAD

**Issue by wangyb-A** [stat545ubc-2023/collaborative-group24#15]
- [x]  Exercise 1: Getting Setup @stat545ubc-2023/group24 
- [x]  Exercise 2: Markdown formatting @shycw1  @thomasbd14 @Sebastian-Santana-Ort 
- [x]  Exercise 3: Merge PR per teammate @stat545ubc-2023/group24 
- [x]  Exercise 4: Github Issues @stat545ubc-2023/group24 
- [x]  Exercise 5: Teamwork Contract @Sebastian-Santana-Ort 
- [x]  Exercise 6: Troubleshooting doc @SillyPasty 
- [x]  Exercise 7: Readme file @thomasbd14 
- [x]  Exercise 8: Submitting Milestone @stat545ubc-2023/group24
