### ISSUE TITLE
Milestone 2 To do list

### ISSUE THREAD

**Issue by wangyb-A** [stat545ubc-2023/collaborative-group24#20]
- [x]  Exercise 0: Merge PR @stat545ubc-2023/group24 
- [x]  Exercise 1: Troubleshooting document @stat545ubc-2023/group24 
    - [x] Exercise 1.1 & 1.2 @Sebastian-Santana-Ort 
    - [x] Exercise 1.3 & 1.4 @shycw1 
    - [x] Exercise 1.5 @thomasbd14 
    - [x] Exercise 1.6 @SillyPasty 
- [x]  Exercise 2: README file @thomasbd14 
- [x]  Exercise 3: Submitting milestone @SillyPasty
